apiVersion: networking.k8s.io/v1
    nginx.ingress.kubernetes.io/rewrite-target: /
kind: Ingress
metadata:
  name: {{ .Release.Name }}-api
spec:
  ingressClassName: {{ .Values.ingress.className }}
  rules:
  - host: {{ .Values.ingress.host }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ .Release.Name }}-api
            port:
              number: 80

